// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzhzlnmwceceaqpqaiez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6aHpsbm13Y2VjZWFxcHFhaWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODg3ODksImV4cCI6MjA2MTQ2NDc4OX0.HuwEPBpOr41cdcnISJ9VSrBFGWrBWEcqGAMqI64mDLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);